### PR TITLE
ci(mergify): add queued labels

### PR DESCRIPTION
**Pull request by sileht**
This change adds the queue position on pull request labels.

### CODE REVIEW

**Review by jd — CHANGES_REQUESTED** [review]
This will add more label as the PR move into the queue.

**Comment by sileht** [comment]
I proposed a simpler version, I don't see how I can known the previous position in queue.

**Comment by jd** [comment]
@sileht we know that version already works, is this still useful?

**Review by jd — APPROVED** [review]

**Comment by sileht** [comment]
> @sileht we know that version already works, is this still useful?

I think it's cool to know from the label that pull request has been queued.

**Pull request merged**
